title: R3DMCS Documentation
baseurl: "/RNA-3D-correspondence"  
url: "https://bgsu-rna.github.io"  
theme: "just-the-docs"  

# Navigation Links
navbar:
  - name: Home
    link: "{{ site.baseurl }}/"
  - name: Help
    link: "{{ site.baseurl }}/help"

# Markdown processing
markdown: kramdown
