---
layout: default
title: "R3DMCS Help Documentation"
nav_order: 2
has_toc: false
---

title: R3DMCS Documentation
baseurl: "/RNA-3D-correspondence"
url: "https://bgsu-rna.github.io"
remote_theme: just-the-docs/just-the-docs

# Enable the jekyll-remote-theme plugin
plugins:
  - jekyll-remote-theme

nav_enabled: true

# Configuration for Just the Docs
# just_the_docs:
#   # Set to true to use a single page's navigation as the sidebar
#   aux_nav:
#     "Help Documentation":
#       - url: "/RNA-3D-correspondence/help"
#         title: "R3DMCS Help Documentation"
#       - url: "/RNA-3D-correspondence/help#input_page"
#         title: "Input Page"
#       - url: "/RNA-3D-correspondence/help#url_access"
#         title: "URL Access"
#       - url: "/RNA-3D-correspondence/help#output_page"
#         title: "Output Page and Examples"
#       - url: "/RNA-3D-correspondence/help#availability"
#         title: "Availability"
#       - url: "/RNA-3D-correspondence/help#limitations"
#         title: "Limitations"

# Markdown processing
markdown: kramdown
