title: R3DMCS Documentation
baseurl: "/RNA-3D-correspondence"  
url: "https://bgsu-rna.github.io"  
remote_theme: just-the-docs/just-the-docs

# Enable the jekyll-remote-theme plugin
plugins:
  - jekyll-remote-theme

# Navigation Links
# navbar:
#   - name: Home
#     link: "{{ site.baseurl }}/"
#   - name: Help
#     link: "{{ site.baseurl }}/help"

just_the_docs:
  # Set the layout to "default" to include the sidebar
  layout: "default"
  # Define the navigation for your help page
  nav_order: 1
  nav:
    - title: "Help Documentation"
      url: "/RNA-3D-correspondence/help"
      children:
        - title: "Input Page"
          url: "#input_page"
        - title: "URL Access"
          url: "#url_access"
        - title: "Output Page and Examples"
          url: "#output_page"
        - title: "Availability"
          url: "#availability"
        - title: "Limitations"
          url: "#limitations"


# Markdown processing
markdown: kramdown
